### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by jmgomezpoveda** [cdown/tzupdate#14]
Whereas the script runs great when executed manually, it'd be great for it to run automatically as soon as there is Internet access.

I have tried manually calling it from /etc/rc.local, but the timezone is not updated (is the Internet connection available at that point?)

Whatever the solution is, it would be great to have it automatically set up upon installation.

**Comment by cdown** [comment]
How this should be set up is distribution specific. rc.local is certainly not the way to go since it's executed potentially before network access.

I definitely don't want to run this on system start *by default* because GeoIP is not perfect. For example, I work at Facebook, and our IP ranges often show America/Los_Angeles just because our AS is registered as being there, even though I'm in London. It would be very annoying to have this happen repeatedly.

I'd suggest that if you really want this, you either:

1. Run tzupdate after the network comes up (with systemd, by specifying `network.target` as a dependency
2. Run tzupdate on a cron every hour or so

I'm not going to have it set up by default on installation though, since this is very intrusive. It should be up to the user what they want to do with the tool, it shouldn't make assumptions about how they want to use it.

**Comment by jmgomezpoveda** [comment]
Well, it's up to the user to test it and if it works for them, have it run automatically, or uninstall the software otherwise.

**Comment by cdown** [comment]
I don't know of anyone (yet) who runs this automatically due to concerns about GeoIP anomalies. If you want to do it, it's not complicated :-)

It is way more intrusive and complicated to assume the user wants to run a (non-daemon!) tool automatically, instead, and it's a bad software packaging pattern.

**Comment by jmgomezpoveda** [comment]
As I usually travel between locations that are properly recognised automatically, I have configured to run automatically, as follows:

I have created a `/home/myuser/.local/bin/tzupdate.service` file, with the content

```
[Unit]
Description=Time zone update
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c "/home/myuser/.local/bin/tzupdate"

[Install]
WantedBy=multi-user.target
```

Then ran `systemctl enable /home/myuser/.local/bin/tzupdate.service`, which has created the symlinks and made it to run automatically under Systemd.

However, this is apparently not sufficient in Ubuntu, and the script was run before there was Internet access. So, I have had to do the following modification:

```
[Unit]
Description=Time zone update
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c "sleep 20; /home/myuser/.local/bin/tzupdate"

[Install]
WantedBy=multi-user.target
```

Not as clean, but it works. I hope this is useful to other frequent flyers.

**Comment by SamHH** [comment]
@jmgomezpoveda I'm not very familiar with systemd, how would I run that as a user service? By default the user is me / unprivileged, and if I try changing user/group to root it... doesn't like that. haha

**Comment by cdown** [comment]
@samhh If you want to run as root, why are you trying to run it as a user service at all?

**Comment by SamHH** [comment]
@cdown New to systemd and don't know best practices! If that's the idiomatic way then I'll do that. :-)

**Comment by dieggsy** [comment]
@ReekyMarko Have you tried using the NetworkManager dispatcher? https://wiki.archlinux.org/index.php/NetworkManager#Network_services_with_NetworkManager_dispatcher

I'm going to be trying this with the script `/etc/NetworkManager/dispatcher.d/10-tzupdate.sh`
```sh
#!/bin/sh
status=$2
case $status in
    up)
        /usr/bin/tzupdate
esac

```

**Comment by ReekyMarko** [comment]
Works like a charm! Thanks a lot :smiley:
